### ISSUE TITLE
Error parsing marker-file with ramps

### ISSUE THREAD

**Issue by MariaCheca** [CartoDB/carto#19] opened 2017-01-03 14:15 UTC
### Problem
When using Builder styling point geometries with the cartocss console, we've found that right now it's not compatible with `marker-file` property with Turbocarto `ramp` value.

For example, given this cartocss:
```
#layer {
  marker-width: 10;
  marker-fill: ramp([name], (#5F4690, #d94bd5, #38A6A5, #0F8554), ("Avenida de América", "Alonso Martínez", "Argüelles", "Colonia Jardín"), "=");
  marker-fill-opacity: 1;
  marker-allow-overlap: true;
  marker-line-width: 3;
  marker-line-color: #FFF;
  marker-line-opacity: 1;

marker-file: ramp([name], (url('https://s3.amazonaws.com/com.cartodb.users-assets.production/maki-icons/circle-stroked-18.svg'), url('https://s3.amazonaws.com/com.cartodb.users-assets.production/maki-icons/star-stroked-18.svg'), '', url('https://s3.amazonaws.com/com.cartodb.users-assets.production/maki-icons/star-stroked-18.svg')), ("Avenida de América", "Alonso Martínez", "Argüelles", "Colonia Jardín"), "=");
}
```

The line corresponding to the `marker-file` with ramp returns an error once the changes are submitted:

```
Syntax error. Line 10: Invalid value for marker-file, the type uri is expected. ramp([name],https://s3.amazonaws.com/com.cartodb.users-assets.production/maki-icons/circle-stroked-18.svg, https://s3.amazonaws.com/com.cartodb.users-assets.production/maki-icons/star-stroked-18.svg, , https://s3.amazonaws.com/com.cartodb.users-assets.production/maki-icons/star-stroked-18.svg,Avenida de América, Alonso Martínez, Argüelles, Colonia Jardín,=) (of type call) was given.
```

### Possible causes
Seems like the parser in charge of detecting syntax errors doesn't recognize a ramp inside a `marker-file` property, as it does in the `marker-fill` one.

### Request
We don't know if there's another accepted way to specify the `marker-file` **using Turbocarto**, in case there isn't any we need to fix the parser to accept this syntax. This is important to develop [this feature](https://github.com/CartoDB/cartodb/issues/11019) properly.

cc @xavijam @rochoa @javierarce

**Comment by rochoa** [comment] 2017-01-03 14:58
The provided Turbo-Carto/CartoCSS is not valid.

```
marker-file: ramp([name], (url('https://s3.amazonaws.com/com.cartodb.users-assets.production/maki-icons/circle-stroked-18.svg'), url('https://s3.amazonaws.com/com.cartodb.users-assets.production/maki-icons/star-stroked-18.svg'), '', url('https://s3.amazonaws.com/com.cartodb.users-assets.production/maki-icons/star-stroked-18.svg')), ("Avenida de América", "Alonso Martínez", "Argüelles", "Colonia Jardín"), "=");
THE PROBLEM IS HERE --->--->--->--->--->--->--->--->--->--->--->--->--->--->--->--->--->--->--->--->--->--->--->--->--->--->--->--->--->--->--->--->--->--->--->--->--->--->--->--->--->--->--->--->--->--->--->--->--->--->--->----^^^
```

That's like sending `marker-file: '';`, which is not valid.

Not a bug.

**Comment by MariaCheca** [comment] 2017-01-03 15:02
Hey @rochoa thanks for answering :)

We've tested it removing the empty string and it returns the same error:

```
#layer {
  marker-width: 10;
  marker-fill: ramp([name], (#5F4690, #1D6996, #38A6A5), ("Avenida de América", "Alonso Martínez", "Argüelles"), "=");
  marker-fill-opacity: 1;
  marker-allow-overlap: true;
  marker-line-width: 3;
  marker-line-color: #FFF;
  marker-line-opacity: 1;
marker-file: ramp([name], (url('https://s3.amazonaws.com/com.cartodb.users-assets.production/maki-icons/circle-stroked-18.svg'), url('https://s3.amazonaws.com/com.cartodb.users-assets.production/maki-icons/star-stroked-18.svg'), url('https://s3.amazonaws.com/com.cartodb.users-assets.production/maki-icons/star-stroked-18.svg')), ("Avenida de América", "Alonso Martínez", "Argüelles"), "=");
}
```

```
Syntax error. Line 9: Invalid value for marker-file, the type uri is expected. ramp([name],https://s3.amazonaws.com/com.cartodb.users-assets.production/maki-icons/circle-stroked-18.svg, https://s3.amazonaws.com/com.cartodb.users-assets.production/maki-icons/star-stroked-18.svg, https://s3.amazonaws.com/com.cartodb.users-assets.production/maki-icons/star-stroked-18.svg,Avenida de América, Alonso Martínez, Argüelles,=) (of type call) was given.
```

**Comment by rochoa** [comment] 2017-01-03 15:36
Is that validation happening server side or client side?

**Comment by MariaCheca** [comment] 2017-01-03 15:51
This error is returned in the client side in Builder cartocss console. We've seen that the error appears after this call: https://github.com/CartoDB/cartodb/blob/master/lib/assets/core/javascripts/cartodb3/helpers/parser-css.js#L94

**Comment by rochoa** [comment] 2017-01-03 16:19
If the problem is client side validation, we need to change the `marker-file` property to accept expressions. Other properties, like [`marker-fill` already supports expressions](https://github.com/CartoDB/carto/blob/f17aea8657ea27f2a660db15dd13b57127e823f9/lib/carto/torque-reference.js#L668-L673), but [marker-file does not support expressions](https://github.com/CartoDB/carto/blob/f17aea8657ea27f2a660db15dd13b57127e823f9/lib/carto/torque-reference.js#L583-L589).

We did something similar in the past for other properties, see https://github.com/CartoDB/carto/commit/1fc486b1b94ffe62f87913b8c2fa213f58a237e3.

**Comment by rochoa** [comment] 2017-01-03 16:24
BTW, server side works because the Turbo-Carto is preprocessed before CartoCSS validation kicks off.

As an alternative, we could have a TurboCarto validator client side doing a dummy transformation, but I'm against it as it could create noise as errors won't match. Which is a similar problem to the current one, we do some validation on the client side that is different than the validation we do server side, which introduces these scenarios where something that will work server side, it's failing in the client side validation.

Why don't we rely on the server side validation, and we have the client side validation? cc @xavijam

**Comment by MariaCheca** [comment] 2017-01-03 17:57
Hum, so Turbocarto doesn't support ramps in `marker-file` or it's just that the validator doesn't recognize that format?

By now we are solving this problem using Cartocss normal syntax, but the best way to do it would be using ramps the same way we do with `marker-fill`.

**Comment by rochoa** [comment] 2017-01-03 18:06
Can you try (and test) to use https://github.com/CartoDB/carto/tree/more-expressions as [cartodb/cartodb package's dependency](https://github.com/CartoDB/cartodb/blob/2e74b82a2c5e22dd8b6d78bd970dd049ea0b5527/package.json#L24)?

That branch has `marker-file` marked as expression compatible.

**Comment by MariaCheca** [comment] 2017-01-04 15:56
@javierarce and I tested it and it works perfectly :D 

Now could it be possible to make a PR to merge the `more-expressions` branch into `master`?

**Comment by rochoa** [comment] 2017-01-04 16:06
Do you expect to use any other property in combination with Turbo-Carto?

**Comment by MariaCheca** [comment] 2017-01-04 16:09
Not in this feature, there are more things to be implemented but don't have anything to do with Turbocarto.

**Comment by rochoa** [comment] 2017-01-04 16:33
Changes are now merged into master branch. @MariaCheca can you verify them there?

**Comment by MariaCheca** [comment] 2017-01-04 16:53
Like a charm ✨ Thank you so much @rochoa!

**Closed** 2017-01-09 09:27 UTC
